# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ 
      (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "ehci_pci" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" = { 
    device = "/dev/disk/by-uuid/fdd1b693-188e-424c-91a1-0a38238e98fe";
    fsType = "btrfs";
    options = [ 
      "subvol=@nixos"
      "discard=async"
      "ssd"
      "noatime"
      "space_cache"
      "compress-force=lzo"
      "autodefrag"
    ];
  };

  fileSystems."/home" = { 
    device = "/dev/disk/by-uuid/fdd1b693-188e-424c-91a1-0a38238e98fe";
    fsType = "btrfs";
    options = [ 
      "subvol=@home"
      "discard=async"
      "ssd"
      "noatime"
      "space_cache"
      "compress-force=lzo"
      "autodefrag"
    ];
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/6B28-CA87";
    fsType = "vfat";
  };
  
  zramSwap = {
    enable = true;
    algorithm = "lz4";
  };
}
