# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ 
      (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "ehci_pci" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" = { 
    device = "/dev/disk/by-uuid/fdd1b693-188e-424c-91a1-0a38238e98fe";
    fsType = "btrfs";
    options = [ 
      "subvol=@nixos"
      "discard=async"
      "ssd"
      "noatime"
      "space_cache"
      "compress-force=zstd:1"
    ];
  };

  fileSystems."/home" = { 
    device = "/dev/disk/by-uuid/fdd1b693-188e-424c-91a1-0a38238e98fe";
    fsType = "btrfs";
    options = [ 
      "subvol=@home"
      "discard=async"
      "ssd"
      "noatime"
      "space_cache"
      "compress-force=zstd:1"
    ];
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/6B28-CA87";
    fsType = "vfat";
  };

  swapDevices = [ 
    { device = "/dev/disk/by-partuuid/de92fdd0-f1d4-4529-a0fd-832f483198fb"; }
  ];

}
